spring:
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/controlchange
    username: potato
    password: 1234
